USE seata_storage;

-- AT模式库存表
CREATE TABLE IF NOT EXISTS t_storage (
  id BIGINT NOT NULL AUTO_INCREMENT,
  product_id VARCHAR(50) NOT NULL,
  total INT NOT NULL,
  used INT NOT NULL DEFAULT 0,
  residue INT NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- TCC模式库存表
CREATE TABLE IF NOT EXISTS t_storage_tcc (
  id BIGINT NOT NULL AUTO_INCREMENT,
  product_id VARCHAR(50) NOT NULL,
  total INT NOT NULL,
  used INT NOT NULL DEFAULT 0,
  frozen INT NOT NULL DEFAULT 0,
  residue INT NOT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_id (product_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- AT模式回滚日志表
CREATE TABLE IF NOT EXISTS undo_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  branch_id BIGINT NOT NULL,
  xid VARCHAR(100) NOT NULL,
  context VARCHAR(128) NOT NULL,
  rollback_info LONGBLOB NOT NULL,
  log_status INT NOT NULL,
  log_created DATETIME NOT NULL,
  log_modified DATETIME NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY ux_undo_log (xid, branch_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;